import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Check, Clock3, MapPin, Megaphone, Phone, Search, ShieldCheck, Star, Tag, UserPlus } from "lucide-react";
import { toast } from "sonner";

const CONTACT = "201014732300";
const categories = ["الكل", "الصحة والطب", "المقاولات والحرف", "التعليم والتدريب", "المطاعم والأغذية", "السيارات", "الخدمات الرقمية", "الأزياء والجمال", "النقل والمواصلات", "خدمات أخرى"];
type Business = { id: string; name: string; category: string | null; subcategory: string; district: string; tag: string; description: string; phone: string | null; whatsapp: string | null; hours_json: string | null; reviews: number; rating: number | null; image_url: string | null; offering_name: string };
type DirectoryResponse = { businesses?: Business[] };
type Hours = Record<string, unknown>;

function Logo() { return <div className="market-logo"><span>✦</span><div><strong>AI DIGITAL SINAI</strong><small>بوابة الخدمات والمنتجات المعتمدة</small></div></div>; }
function parseHours(value: string | null): Hours { try { return value ? JSON.parse(value) as Hours : {}; } catch { return {}; } }
function isBusinessOpen(business: Business) {
  const hours = parseHours(business.hours_json);
  const now = new Date();
  const day = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"][now.getDay()];
  const entry = hours[day] ?? hours[String(now.getDay())] ?? hours["daily"];
  if (entry === "24h" || entry === "24 ساعة" || entry === true) return true;
  const range = typeof entry === "string" ? entry : entry && typeof entry === "object" ? (entry as { open?: string; close?: string }).open && (entry as { open?: string; close?: string }).close ? `${(entry as { open: string }).open}-${(entry as { close: string }).close}` : "" : "";
  const match = range.match(/(\d{1,2}:?\d{0,2})\s*[-–]\s*(\d{1,2}:?\d{0,2})/);
  if (!match) return false;
  const toMinutes = (time: string) => { const [hour, minute = "0"] = time.split(":"); return Number(hour) * 60 + Number(minute); };
  const current = now.getHours() * 60 + now.getMinutes();
  const open = toMinutes(match[1]); const close = toMinutes(match[2]);
  return close < open ? current >= open || current <= close : current >= open && current <= close;
}
function formatHours(value: string | null) { const hours = parseHours(value); const today = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"][new Date().getDay()]; const entry = hours[today] ?? hours[String(new Date().getDay())] ?? hours["daily"]; if (entry === "24h" || entry === "24 ساعة" || entry === true) return "24 ساعة"; if (typeof entry === "string") return entry; if (entry && typeof entry === "object") { const item = entry as { open?: string; close?: string }; if (item.open && item.close) return `${item.open} – ${item.close}`; } return "الساعات غير مسجلة"; }

export default function Marketplace() {
  const [category, setCategory] = useState("الكل");
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [subscribed, setSubscribed] = useState(false);
  const [query, setQuery] = useState("");
  const [businesses, setBusinesses] = useState<Business[]>([]);
  const [directoryState, setDirectoryState] = useState<"loading" | "ready" | "error">("loading");
  const [directoryError, setDirectoryError] = useState("");
  useEffect(() => { const controller = new AbortController(); setDirectoryState("loading"); fetch(`/api/platform/marketplace/directory?query=${encodeURIComponent(query)}&category=${encodeURIComponent(category === "الكل" ? "" : category)}`, { signal: controller.signal, headers: { Accept: "application/json" } }).then(async (response) => { if (!response.ok) throw new Error("directory request failed"); const payload = await response.json() as DirectoryResponse; setBusinesses(payload.businesses ?? []); setDirectoryState("ready"); }).catch((error: unknown) => { if ((error as { name?: string }).name !== "AbortError") { setDirectoryState("error"); setDirectoryError("تعذر تحميل بيانات الدليل من قاعدة البيانات."); } }); return () => controller.abort(); }, [category, query]);
  const filtered = useMemo(() => businesses, [businesses]);
  const subscribe = (event: FormEvent) => { event.preventDefault(); if (!name.trim() || !phone.trim()) { toast.error("أدخل الاسم ورقم الموبايل أولًا"); return; } setSubscribed(true); toast.success("تم تسجيل طلبك لتلقي العروض"); };
  const share = async (business: Business) => { if (navigator.share) await navigator.share({ title: business.name, text: business.description, url: window.location.href }); else { await navigator.clipboard?.writeText(window.location.href); toast.success("تم نسخ رابط الدليل"); } };
  return <main dir="rtl" className="marketplace-page">
    <header className="marketplace-header"><div className="market-container market-header-inner"><a href="#top" aria-label="AI Digital Sinai"><Logo /></a><div className="market-location"><MapPin size={15} /> العريش <span>⌄</span></div><a className="add-business" href="/app"><UserPlus size={17} /> أضف نشاطك <b>مجانًا</b></a></div></header>
    <section id="top" className="market-container contact-section"><div className="contact-card"><div className="service-badge">خدمة 24 ساعة</div><div className="contact-copy"><h1>تواصل معنا للإعلانات والاقتراحات</h1><p>تريد الإعلان عن نشاطك أو متجرك، أو لديك اقتراح لتطوير المنصة؟ تواصل معنا مباشرة:</p><div className="contact-actions"><a href={`tel:+${CONTACT}`} className="market-button primary"><Phone size={18} /> اتصال</a><a href={`https://wa.me/${CONTACT}`} className="market-button whatsapp"><span>◉</span> واتساب</a></div></div><div className="megaphone"><Megaphone size={42} /></div></div></section>
    <section className="market-container subscribe-card"><div><span className="section-label"><Tag size={16} /> عروض حصرية</span><h2>اشترك في عروض وتخفيضات العريش الحصرية <small>(اختياري)</small></h2><p>سجّل اسمك ورقم هاتفك لنرسل لك أحدث العروض والخصومات مباشرة على واتساب.</p></div>{subscribed ? <div className="subscribed-message"><Check size={22} /> تم تفعيل استقبال العروض</div> : <form onSubmit={subscribe} className="subscribe-form"><input aria-label="الاسم بالكامل" value={name} onChange={(e) => setName(e.target.value)} placeholder="الاسم بالكامل" /><input aria-label="رقم الموبايل" value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="رقم الموبايل (مثال: 010...)" inputMode="tel" /><button className="market-button dark">🔔 تفعيل العروض</button></form>}</section>
    <section className="market-container directory-section"><div className="directory-heading"><div><span className="section-label">دليل موثوق</span><h2>أقسام الدليل والخدمات</h2><p>اختر القسم لاستعراض مقدمي الخدمات المعتمدين</p></div><div className="result-count">تم العثور على <strong>{directoryState === "loading" ? "…" : filtered.length}</strong> خدمة معتمدة</div></div><div className="market-search"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ابحث عن نشاط أو خدمة أو حي" aria-label="البحث في الدليل" /></div><div className="category-grid">{categories.map((item) => <button key={item} className={category === item ? "selected" : ""} onClick={() => setCategory(item)}>{item === "الكل" ? "✦" : "◈"} {item}</button>)}</div></section>
    <section className="market-container listing-section"><div className="listing-heading"><div><span className="section-label">نتائج الدليل</span><h2>منشآت وخدمات حولك</h2></div><span className="approved-note"><ShieldCheck size={16} /> منشورة بعد مراجعة</span></div>{directoryState === "loading" && <div className="empty-directory">جارٍ تحميل الأنشطة المعتمدة من قاعدة البيانات…</div>}{directoryState === "error" && <div className="empty-directory">{directoryError}</div>}{directoryState === "ready" && <><div className="business-grid">{filtered.map((business) => { const open = isBusinessOpen(business); return <article className="business-card" key={business.id}><div className="business-image"><img src={business.image_url || "/manus-storage/sinai-market_86fb201f.jpg"} alt="" /><span className={`open-status ${open ? "open" : "closed"}`}>{open && <i />} {open ? "مفتوح ومتاح الآن" : "مغلق حاليًا"}</span><span className="business-subcategory">{business.subcategory}</span><div className="business-title"><h3>{business.name}</h3><span>{business.district}</span></div></div><div className="business-body"><div className="rating-row"><span><b>{business.reviews}</b> تقييم</span><span className="stars">{business.rating ?? "—"} {business.rating !== null && <Star size={14} fill="currentColor" />} <button onClick={() => toast("سيتم فتح نموذج التقييم بعد تسجيل الدخول")}>قيّم الآن</button></span></div><div className="business-meta"><span><Clock3 size={15} /> {formatHours(business.hours_json)}</span><span className="service-tag">{business.tag}</span></div><p>{business.description || business.offering_name}</p><div className="business-actions"><button className="share-button" onClick={() => share(business)} aria-label={`مشاركة ${business.name}`}>↗</button>{business.whatsapp ? <a className="market-button whatsapp" href={`https://wa.me/${business.whatsapp}`}><span>◉</span> واتساب</a> : <span className="market-button whatsapp" aria-disabled="true"><span>◉</span> واتساب</span>}{business.phone ? <a className="market-button primary" href={`tel:+${business.phone}`}><Phone size={15} /> اتصال</a> : <span className="market-button primary" aria-disabled="true"><Phone size={15} /> اتصال</span>}</div></div></article>; })}</div>{filtered.length === 0 && <div className="empty-directory">لا توجد منشآت أو خدمات معتمدة في قاعدة البيانات لهذا البحث.</div>}</>}</section>
    <footer className="marketplace-footer"><div className="market-container footer-grid"><div><Logo /><p>دليل محلي يقرّبك من الخدمات والمنتجات المعتمدة في شمال سيناء.</p></div><div><span className="footer-heading">روابط موثوقة</span><a href="/app">لوحة تحكم الأدمن 🔒</a><a href="#top">تحديث لحظي Real-time</a><a href="/سياسة-الخصوصية-AI-Digital-Sinai.md">سياسة الخصوصية</a></div></div><div className="market-container trust-line"><ShieldCheck size={15} /> كل نشاط في هذا الدليل يمر بمراجعة قبل الظهور</div></footer>
  </main>;
}
