import { useEffect, useState, type FormEvent } from "react";
import { createBusinessOsSalesReturn, loadSalesOrder, loadSalesOrders, type SalesOrder, type SalesOrderDetail } from "@/lib/businessOsApi";

type Props = { headers: Record<string, string> };
const messageFor = (error: unknown) => (error instanceof Error ? error.message : "تعذر تنفيذ المرتجع من الخادم.");
export default function BusinessOsSalesReturnsPanel({ headers }: Props) {
  const [orders, setOrders] = useState<SalesOrder[]>([]); const [detail, setDetail] = useState<SalesOrderDetail | null>(null); const [state, setState] = useState("loading"); const [message, setMessage] = useState(""); const [quantity, setQuantity] = useState("1"); const [reason, setReason] = useState("مرتجع من واجهة التشغيل"); const [busy, setBusy] = useState(false);
  const refresh = async () => { setState("loading"); try { setOrders(await loadSalesOrders(headers)); setState("ready"); } catch (error) { setMessage(messageFor(error)); setState("error"); } };
  useEffect(() => { void refresh(); }, [headers.authorization, headers["x-tenant-id"]]);
  const open = async (id: string) => { try { setDetail(await loadSalesOrder(id, headers)); setMessage(""); } catch (error) { setMessage(messageFor(error)); } };
  const submit = async (event: FormEvent<HTMLFormElement>, item: SalesOrderDetail["items"][number]) => { event.preventDefault(); const amount = Number(quantity); if (!detail || !Number.isSafeInteger(amount) || amount <= 0 || amount > item.quantity) { setMessage("كمية المرتجع يجب أن تكون موجبة ولا تتجاوز الكمية المباعة."); return; } setBusy(true); try { await createBusinessOsSalesReturn({ orderId: detail.order.id, orderItemId: item.id, productId: item.product_id, quantity: amount, unitRefundCents: item.unit_price_cents, reason }, headers); await refresh(); await open(detail.order.id); setMessage("تم تسجيل Sales Return وتحديث Inventory وLedger وAudit."); } catch (error) { setMessage(messageFor(error)); } finally { setBusy(false); } };
  if (state === "loading") return <section className="mobile-plan-card" aria-label="إدارة مرتجعات المبيعات الحقيقية"><h2>مرتجعات المبيعات</h2><div role="status">جارٍ تحميل الطلبات من الخادم...</div></section>;
  if (state === "error") return <section className="mobile-plan-card" aria-label="إدارة مرتجعات المبيعات الحقيقية"><h2>مرتجعات المبيعات</h2><div role="alert">{message}<button className="mobile-command-button" onClick={() => void refresh()}>إعادة المحاولة</button></div></section>;
  return <section className="mobile-plan-card" aria-label="إدارة مرتجعات المبيعات الحقيقية"><small>Returns · /api/platform/returns · Inventory + Ledger</small><h2>مرتجعات المبيعات</h2>{orders.length ? orders.map((order) => <article className="mobile-data-row" key={order.id}><b>{order.customer_name ?? "عميل نقدي"} · {order.state}</b><span>{order.id} · الإجمالي {order.total_cents} cents</span><button className="mobile-command-button" onClick={() => void open(order.id)}>فتح الطلب للمرتجع</button></article>) : <div className="mobile-empty"><b>لا توجد طلبات قابلة للمرتجع</b><span>سيظهر الطلب الحقيقي هنا بعد إنشائه.</span></div>}{detail && <section className="mobile-command-note" aria-label="تفاصيل مرتجع المبيعات"><button className="mobile-back-button" type="button" onClick={() => setDetail(null)}>إغلاق التفاصيل</button><h3>طلب {detail.order.id}</h3>{detail.items.map((item) => <article className="mobile-data-row" key={item.id}><b>{item.product_name}</b><span>المباع: {item.quantity} · سعر الوحدة: {item.unit_price_cents}</span><form onSubmit={(event) => void submit(event, item)}><input aria-label={`كمية مرتجع ${item.product_name}`} type="number" min="1" max={item.quantity} value={quantity} onChange={(event) => setQuantity(event.target.value)} /><input aria-label="سبب مرتجع المبيعات" value={reason} onChange={(event) => setReason(event.target.value)} /><button className="mobile-command-button" type="submit" disabled={busy}>{busy ? "جارٍ التنفيذ..." : "تسجيل Sales Return"}</button></form></article>)}</section>}{message && <div className="mobile-command-note" role="status">{message}</div>}</section>;
}
